### ISSUE TITLE
Document Map.filter and Map.reject

### ISSUE THREAD

**Issue by ospencer** [grain-lang/grain-lang.org#116]
ref: https://github.com/grain-lang/grain/pull/344

**Comment by ohana54** [comment]
Hey, me again :)
Would you like me to add docs for these methods? Same goes for the new List methods I added. 
I'm pretty busy at work but if it's not too complicated I'd love to give it a try.

**Comment by ospencer** [comment]
Of course, that'd be awesome! 👏 

The docs are all in Markdown, and they've got a pretty consistent format. Here's where the Map docs are: https://github.com/grain-lang/grain-lang.org/blob/master/src/stdlib/map.md

Once you open a PR, the bot will post a deploy preview, so no need to even run the site on your computer!

**Comment by ohana54** [comment]
Done, I hope it's ok I did both in a single PR.
Note I was able to run locally, but only after cloning vscode-grain into the folder, since it was looking for syntax related files there:
`no such file or directory, open './vscode-grain/syntaxes/grain.json'`

**Comment by ospencer** [comment]
Oh, yup, somehow the README is missing a line to pull the submodules. Thanks for doing that!
