### ISSUE TITLE
Hello world

### ISSUE THREAD

**Issue by pierreprinetti** [grain-lang/grain-lang.org#12]
As a very beginner, I would find a "hello world" example useful.

Being able to see the results in the interactive console would also help me with a fast confirmation that my setup is OK.

**Comment by ospencer** [comment]
Certainly! The website is actually going to go through a massive redeisgn in the near-ish future, and we'll have a real `Getting Started` page with something like a hello world program.

**Comment by ospencer** [comment]
I know it's been awhile, but we now have a proper Hello World example as part of our [guide](https://grain-lang.org/guide)! You can find it here: https://grain-lang.org/guide/essentials/hello_world.
