### ISSUE TITLE
discord verification

### ISSUE THREAD

**Issue by av8ta** [grain-lang/grain-lang.org#305]
I realise this is the wrong place, but how to message on discord when unable to verify!

![image](https://user-images.githubusercontent.com/17036768/180898113-96c6af26-0035-4f0d-8735-2e67ec70bcb8.png)

My phone went in the pool about two months ago. I don't miss it in the slightest. In fact, life is so much better without a phone! Well, it was, until I could no longer chat to the good people of grain :sob:

**Comment by phated** [comment]
Thanks for the context! I've created a new role for users that can't verify their phone number and created this thread where people can ask for approval: https://github.com/grain-lang/grain/discussions/1370

**Comment by av8ta** [comment]
Thanks for sorting it out :)
