### ISSUE TITLE
document spread operator

### ISSUE THREAD

**Issue by almibe** [grain-lang/grain-lang.org#340]
The spread operator is mentioned in passing here https://grain-lang.org/docs/stdlib/pervasives#Pervasives-cons, but I don't think it is documented as its own feature?

**Comment by ospencer** [comment]
It's mentioned here: https://grain-lang.org/docs/guide/lists#Creating-Lists

Did you mean in the stdlib docs? I don't think it'll really end up there, but it'll definitely be a part of the language reference.

**Comment by almibe** [comment]
Ohh my bad, I'll close this.
